# google_mlkit_text_recognition references optional script recognizers
# (chinese/devanagari/japanese/korean) whose classes aren't bundled unless
# those variants are depended on. This app only uses the Latin recognizer.
# Rules generated by R8 (missing_rules.txt).
-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**
